language: python
sudo: required
dist: trusty
services:
  - docker
env:
  - OS_DISTRO=centos OS_VERSION=7 TOXENV=linters
  - OS_DISTRO=centos OS_VERSION=7 TOXENV=functional_1.9.4
  - OS_DISTRO=centos OS_VERSION=7 TOXENV=functional_2.1.0
  - OS_DISTRO=centos OS_VERSION=7 TOXENV=functional_stable
  - OS_DISTRO=ubuntu OS_VERSION=16.04 TOXENV=linters
  - OS_DISTRO=ubuntu OS_VERSION=16.04 TOXENV=functional_1.9.4
  - OS_DISTRO=ubuntu OS_VERSION=16.04 TOXENV=functional_2.1.0
  - OS_DISTRO=ubuntu OS_VERSION=16.04 TOXENV=functional_stable
before_install:
  - sudo docker pull ${OS_DISTRO}:${OS_VERSION}
install:
  - sudo docker run --detach --volume="${PWD}":/opt/test:rw --name ${OS_DISTRO}-${OS_VERSION} ${OS_DISTRO}:${OS_VERSION} sleep 300
  - sudo docker exec ${OS_DISTRO}-${OS_VERSION} yum -y install epel-release '@Development Tools' python-devel git libffi-devel openssl-devel libselinux-python
  - sudo docker exec ${OS_DISTRO}-${OS_VERSION} /bin/bash -c 'curl https://bootstrap.pypa.io/get-pip.py | python'
  - sudo docker exec ${OS_DISTRO}-${OS_VERSION} pip install tox
script:
  - sudo docker exec ${OS_DISTRO}-${OS_VERSION} /bin/bash -c "cd /opt/test; tox -e ${TOXENV}"
after_script:
  - sudo docker stop ${OS_DISTRO}-${OS_VERSION}
notifications:
  slack:
    rooms:
      secure: uGk3oNKE6M7h+c2wMurecULb73tyyhkjM3J/FwlDr7a7SO2kM4Vki5+4UFJV3x7k0TQ2+U5Iu2m63oaAHtiEWqiVJEIIuYKu3oH/mPnVHVilU8t4elZ4d6IQo2UEzM0B0HmkUA5A6o5TJt0Y4msXHq4jXYoy6/+ot8qWzSfgpER5H1/woMFIVrmlAursVfoDB2yIOoGSFRS5P3CjoPa2yEFpPYemsiUsDClj+blt4iXqgH9Uc65Gucen1a5KnxjJsPwzXJhWcIB8CpHCFsOGOguk+tvFlJxtFuAWRNEvk59tMX82pAzIOKNmu4cL9Y4EnCPJNYT8c8NWvJoPuxfJU6THZ8S+WDIJdWSlENWyGqebDiOJkVtXBe6+YMPt5afuoUlD++usCEO9EOTajpJZcNnz8fMhsFYjn0eMn5jStCIWO/4W8JFShNFwQ3HLuJ9/EZYDvGWSIn4XXhU+wbM90BM+TeZqAdzWcsKN6TqUm3G8d5jrVGFteb1W85LB3MFVaJCdrsjwYVrFl71ojaxK7NBuzUZYgOTtDd6MC6FtkAfVyWzEfpa5rGge8TT/TwbhBVYCWOB29Ax/DgPXUtH2AaJv8on3q2R2vkmEoB7y6uz4BddPwbGR2sMz19IIj/i+KbOlQ+xtzoa+e+CTUdSJW72LSJ+1sLoKYOYz6mTU7cg=
